spring.application.name=web
#Connection URL for PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/NewBig

# Database Credentials
spring.datasource.username=postgres
spring.datasource.password=1234

# PostgreSQL Driver
#spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate DDL Auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto=update

# Show SQL queries in the console (Optional)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Database Platform/Dialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=8081